TMS/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TMS.DataAccess.Data.Repository.IRepository;
using TMS.Utility;
using Constant = TMS.Utility.Constant;

namespace TMS.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TaskController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TaskController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return Json(new { data = _unitOfWork.Task.GetAll(includeProperties: "Priority,ApplicationUser", filter: c => c.UserId == claim.Value && (c.Status == Constant.StatusStarted || c.Status == Constant.StatusInProgress)) });
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Task.GetFirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Task.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }

        [HttpPost("{id}")]
        public IActionResult Close(int id)
        {
            var objFromDb = _unitOfWork.Task.GetFirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while closing the task" });
            }
            objFromDb.Status = Constant.StatusClosed;
            objFromDb.ClosedOn = DateTime.Today;
            _unitOfWork.Save();
            return Json(new { success = true, message = "Task closed successful" });
        }
    }
}

TMS/Controllers/WorkdayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TMS.DataAccess.Data.Repository.IRepository;


namespace TMS.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class WorkdayController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public WorkdayController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get(int? id)
        {
            return Json(new { data = _unitOfWork.WDay.GetAll(includeProperties: "Task", filter: c => c.TaskId == id) });
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.WDay.GetFirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.WDay.Remove(objFromDb);
            _unitOfWork.Save();
            _unitOfWork.Task.UpdateTotalOfHours(objFromDb.TaskId);
            return Json(new { success = true, message = "Delete successful" });
        }
    }
}

TMS/Pages/Admin/Task/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMS.DataAccess.Data.Repository.IRepository;
using TMS.Models.ViewModels;
using TMS.Utility;

namespace TMS.Pages.Admin.Task
{
    public class DetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public DetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public TaskViewModel TaskObj { get; set; }
        public void OnGet(int id)
        {
            TaskObj = new TaskViewModel()
            {
                UserList = _unitOfWork.ApplicationUser.GetUserListForDropDown(),
                Priorities = _unitOfWork.Priority.GetPriorityListForDropDown(),
                Task = _unitOfWork.Task.GetFirstOrDefault(includeProperties: "Priority,ApplicationUser", filter: c => c.Id == id)
            };
        }

        public IActionResult OnPostProgress()
        {
            var task = _unitOfWork.Task.GetFirstOrDefault(c => c.Id == TaskObj.Task.Id);
            task.Status = Constant.StatusInProgress;
            _unitOfWork.Save();
            return RedirectToPage("Details", new { id = task.Id});
        }

        public IActionResult OnPostClose()
        {
            var task = _unitOfWork.Task.GetFirstOrDefault(c => c.Id == TaskObj.Task.Id);
            //task.Status = Constant.StatusClosed;
            //_unitOfWork.Save();
            return RedirectToPage("Details", new { id = task.Id });
        }
    }
}

TMS/Pages/Admin/Task/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMS.Utility;

namespace TMS.Pages.Admin.Task
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TMS/Pages/Admin/Task/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMS.DataAccess.Data.Repository.IRepository;
using TMS.Models.ViewModels;
using TMS.Utility;

namespace TMS.Pages.Admin.Task
{

    [Authorize]
    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public UpsertModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public TaskViewModel TaskObj { get; set; }

        public IActionResult OnGet(int? id)
        {
            TaskObj = new TaskViewModel()
            {
                UserList = _unitOfWork.ApplicationUser.GetUserListForDropDown(),
                Priorities = _unitOfWork.Priority.GetPriorityListForDropDown(),
                Task = new Models.CTask()
            };
            if (id != null)
            {
                TaskObj.Task = _unitOfWork.Task.GetFirstOrDefault(u => u.Id == id);
                if (TaskObj.Task == null)
                {
                    return NotFound();
                }
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (TaskObj.Task.Id == 0)
            {
                TaskObj.Task.CreatedOn = DateTime.Today;
                TaskObj.Task.Status = Constant.StatusStarted;
                _unitOfWork.Task.Add(TaskObj.Task);
            }
            else
            {
                _unitOfWork.Task.Update(TaskObj.Task);
            }
            _unitOfWork.Save();
            return RedirectToPage("./Index");
        }
    }
}

TMS/Pages/Admin/Task/Workday.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMS.DataAccess.Data.Repository.IRepository;
using TMS.Models;

namespace TMS.Pages.Admin.Task
{
    public class WorkdayModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public WorkdayModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public CDay DayObj { get; set; }

        public IActionResult OnGet(int? taskId, int? id)
        {
            DayObj = new CDay()
            {
                Task = _unitOfWork.Task.GetFirstOrDefault(u => u.Id == taskId),
                TaskId = Convert.ToInt32(taskId)
            };
            if (id != null)
            {
                DayObj = _unitOfWork.WDay.GetFirstOrDefault(includeProperties: "Task", filter: c => c.Id == id);
                if (DayObj == null)
                {
                    return NotFound();
                }
            }
            return Page();
        }

        //public IActionResult OnGet(int? id)
        //{
        //    DayObj = new CDay()
        //    {
        //        Task = _unitOfWork.Task.GetFirstOrDefault(u => u.Id == id),
        //        TaskId = Convert.ToInt32(id)
        //    };
        //    if (id != null)
        //    {
        //        DayObj = _unitOfWork.WDay.GetFirstOrDefault(u => u.Id == id);
        //        if (DayObj == null)
        //        {
        //            return NotFound();
        //        }
        //    }
        //    return Page();
        //}

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            CDay day = _unitOfWork.WDay.GetFirstOrDefault(d => d.Date == DayObj.Date && d.TaskId == DayObj.TaskId);
            
            if (DayObj.Id == 0)
            {
                if (day != null)
                {
                    // TODO Send a warning back if same day added
                    // Currently day will be updated
                    _unitOfWork.WDay.Update(DayObj);
                }
                else
                {
                    DayObj.CreatedOn = DateTime.Today;
                    DayObj.Day = DayObj.Date.DayOfWeek.ToString();
                    _unitOfWork.WDay.Add(DayObj);
                }
                
            }
            else
            {
                _unitOfWork.WDay.Update(DayObj);
            }
            
            _unitOfWork.Save();
            _unitOfWork.Task.UpdateTotalOfHours(DayObj.TaskId);
            return RedirectToPage("./Details", new { id = DayObj.TaskId });
        }
    }
}

TMS/Pages/Admin/Task/Details.cshtml
@page
@model TMS.Pages.Admin.Task.DetailsModel
@using TMS.Utility
@{
    ViewData["Title"] = "Details";
}

<div class="">
    <form method="post">
        <input type="hidden" asp-for="TaskObj.Task.Id" />
        <input type="hidden" asp-for="TaskObj.Task" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="container backgroundWhite">
            <div class="card">
                <div class="card-header bg-light text-light ml-0 row container">
                    <div class="col-12 col-md-6">
                        <h3 class="text-secondary"><strong>Details:</strong> @Model.TaskObj.Task.Name</h3>
                    </div>
                    <div class="col-12 col-md-6 text-md-right">
                        @if (Model.TaskObj.Task.TotalOfHours > 0)
                        {
                            <h3 class="text-muted"> @((Model.TaskObj.Task.TotalOfHours).ToString() + " hours")</h3>
                        }
                        else
                        {
                            <h3 class="text-muted"> @((Model.TaskObj.Task.TotalOfHours).ToString() + " hour")</h3>
                        }

                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-8">
                                <div class="row">

                                    <div class="col-12">

                                        <div class="form-group row">
                                            <div class="col-3">
                                                <label asp-for="TaskObj.Task.Description"></label>
                                            </div>
                                            <div class="col-9">
                                                <textarea class="form-control" asp-for="TaskObj.Task.Description" id="txtDesc" style="height:80px;" readonly></textarea>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <div class="col-3">
                                                <label asp-for="TaskObj.Task.RequestDate"></label>
                                            </div>
                                            <div class="col-9">
                                                <input class="form-control" id="datepicker" value="@Model.TaskObj.Task.RequestDate.ToShortDateString()" type="text" asp-for="TaskObj.Task.RequestDate" data-val="true" readonly/>
                                                <span class="text-danger" asp-validation-for="TaskObj.Task.RequestDate"></span>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <div class="col-3">
                                                <label asp-for="TaskObj.Task.Customer"></label>
                                            </div>
                                            <div class="col-9">
                                                <input class="form-control" asp-for="TaskObj.Task.Customer" readonly/>
                                                <span class="text-danger" asp-validation-for="TaskObj.Task.Customer"></span>
                                            </div>
                                        </div>


                                        <div class="form-group row">
                                            <div class="col-3">
                                                <label asp-for="TaskObj.Task.UserId"></label>
                                            </div>
                                            <div class="col-9">
                                                <input class="form-control" asp-for="TaskObj.Task.ApplicationUser.FullName" readonly/>
                                                <span class="text-danger" asp-validation-for="TaskObj.Task.ApplicationUser.FullName"></span>
                                            </div>
                                        </div>


                                    </div>

                                </div>
                            </div>

                            <div class="col-12 col-lg-4 p-1 text-center">
                                <span class="badge badge-primary">@Model.TaskObj.Task.Priority.Name</span>
                                <span class="badge badge-warning">@Model.TaskObj.Task.Status</span>

                                <div class="col pt-5">
                                    @if (Model.TaskObj.Task.Status == Constant.StatusStarted)
                                    {
                                        <div class="pt-3">
                                            <button type="submit" asp-page-handler="Progress" class="btn btn-warning btn-square form-control btn-lg" style="height:35px;width:200px;font-size:14px;">@Constant.StatusInProgress</button>
                                        </div>
                                    }

                                    <div class="pt-3">
                                        <a asp-page="Index" class="btn btn-success btn-square form-control btn-lg" style="height:35px;width:200px;font-size:14px;">Back to List</a>
                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>
                </div>

                <div class="card-footer">

                    <div class="row pt-3">
                        <div class="col-6">
                            <h4 class="text-secondary">Workday List</h4>
                        </div>
                        <div class="col-6 text-right pt-2">
                            <a asp-page="Workday" asp-route-taskId="@Model.TaskObj.Task.Id" asp-route-id="" class="btn btn-secondary"><i class="fas fa-fa-plus"></i> &nbsp; Add Day</a>
                        </div>
                    </div>
                    <br /><br />
                    <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Day</th>
                                <th>Date</th>
                                <th>No Hours</th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>

                </div>
            </div>
        </div>
    </form>
</div>


@section Scripts{

    <script>

        var dataTable;

        $(document).ready(function () {
            loadList();
        });

        function loadList() {
            var url = "/api/workday?id=" + @Model.TaskObj.Task.Id;
            dataTable = $('#DT_load').DataTable({
                "ajax": {
                    "url": url,
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "date", "width": "30%" },
                    { "data": "day", "width": "25%" },
                    { "data": "hours", "width": "15%" },
                    {
                        "data": "id",
                        "render": function (data) {
                            return ` <div class="text-center">
                                <a href="/Admin/Task/workday?id=${data}" class="btn btn-success text-white" style="cursor:pointer; width:100px;">
                                    <i class="far fa-edit"></i> Edit
                                </a>
                                <a class="btn btn-danger text-white" style="cursor:pointer; width:100px;" onclick=Delete('/api/workday/'+${data})>
                                    <i class="far fa-trash-alt"></i> Delete
                                </a>
                    </div>`;
                        }, "width": "30%"
                    }
                ],
                "language": {
                    "emptyTable": "no data found."
                },
                "width": "100%"
            });
        }

        function Delete(url) {
            swal({
                title: "Are you sure you want to Delete?",
                text: "You will not be able to restore the data!",
                icon: "warning",
                buttons: true,
                dangerMode: true
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        success: function (data) {
                            if (data.success) {
                                toastr.success(data.message);
                                dataTable.ajax.reload();
                            }
                            else {
                                toastr.error(data.message);
                            }
                        }
                    });
                }
            });
        }

    </script>

    <script>

        tinymce.init({
            selector: 'textarea',
            plugins: "lists",
            menubar: 'file edit format'
        });

    </script>

}

TMS/Pages/Admin/Task/Index.cshtml
@page
@model TMS.Pages.Admin.Task.IndexModel

<div class="border backgroundWhite container">
    <div class="row">
        <div class="col-6">
            <h2 class="text-secondary">Task List</h2>
        </div>
        <div class="col-6 text-right pt-2">
            <a asp-page="Upsert" class="btn btn-secondary"><i class="fas fa-fa-plus"></i> &nbsp; New Task</a>
        </div>
    </div>
    <br /><br />
    <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Requested Date</th>
                <th>Hours</th>
                <th>Priority</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/task.js"></script>
}

TMS/Pages/Admin/Task/Upsert.cshtml
@page
@model TMS.Pages.Admin.Task.UpsertModel

<form method="post" asp-action="Upsert">
    <div class="container">
        <div class="row px-2 mx-2 backgroundWhite border">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (Model.TaskObj.Task.Id != 0)
            {
                <input type="hidden" asp-for="TaskObj.Task.Id" />
            }

            <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                <h2 class="text-secondary">@(Model.TaskObj.Task.Id != 0 ? "Update" : "Create") Task</h2>
            </div>

            <div class="col-8 pt-3">

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="TaskObj.Task.Name"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="TaskObj.Task.Name" />
                        <span class="text-danger" asp-validation-for="TaskObj.Task.Name"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="TaskObj.Task.Description"></label>
                    </div>
                    <div class="col-9">
                        <textarea class="form-control" asp-for="TaskObj.Task.Description" id="txtDesc" style="height:80px;"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="TaskObj.Task.RequestDate"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" id="datepicker" value="@Model.TaskObj.Task.RequestDate.ToShortDateString()" type="text" asp-for="TaskObj.Task.RequestDate" data-val="true"/>
                        <span class="text-danger" asp-validation-for="TaskObj.Task.RequestDate"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="TaskObj.Task.UserId"></label>
                    </div>
                    <div class="col-9">
                        @Html.DropDownListFor(m => m.TaskObj.Task.UserId,
                                                    Model.TaskObj.UserList,
                                                    "- Assign to -",
                                                    new { @class = "form-control" })
                        <span class="text-danger" asp-validation-for="TaskObj.Task.UserId"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="TaskObj.Task.Priority"></label>
                    </div>
                    <div class="col-9">
                        @Html.DropDownListFor(m => m.TaskObj.Task.PriorityId,
                                                    Model.TaskObj.Priorities,
                                                    "- Select Priority -",
                                                    new { @class = "form-control" })
                        <span class="text-danger" asp-validation-for="TaskObj.Task.PriorityId"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="TaskObj.Task.Customer"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="TaskObj.Task.Customer" />
                        <span class="text-danger" asp-validation-for="TaskObj.Task.Customer"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-9 offset-3">
                        <div class="row">
                            <div class="col-6">
                                @*<button type="submit" class="btn btn-primary form-control">@(Model.TaskObj.Task.Id != 0 ? "Update" : "Create")</button>*@
                                <button type="submit" id="btnPlaceOrder" onclick="return validateInput()" value="Place Order" class="btn btn-primary form-control">
                                    @(Model.TaskObj.Task.Id != 0 ? "Update" : "Create")
                                </button>
                            </div>
                            <div class="col-6">
                                <a asp-page="./Index" class="btn btn-success form-control">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
    <script>
        //tinymce.init({
        //    selector: 'textarea',
        //    plugins: "lists",
        //    menubar: 'file edit format'
        //});

        $(function () {
            $("#datepicker").datepicker({
                dateFormat: 'dd.MM.yy',
                changeMonth: true,
                changeYear: true,
                minDate: new Date()
            });
        })
    </script>
}

TMS/Pages/Admin/Task/Workday.cshtml
@page
@model TMS.Pages.Admin.Task.WorkdayModel

<form method="post" asp-action="Upsert">
    <div class="container">
        <div class="row px-2 mx-2 backgroundWhite border">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DayObj.TaskId" />
            @{
                var requestedate = Model.DayObj.Task.RequestDate;
                var currentdate = DateTime.Today;
            }
            @if (Model.DayObj.Id != 0)
            {
                <input type="hidden" asp-for="DayObj.Id" />
            }

            <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                <h2 class="text-secondary">@(Model.DayObj.Id != 0 ? "Update" : "Add") Workday</h2>
            </div>

            <div class="col-8 pt-3">

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="@requestedate"></label>
                    </div>
                    <div class="col-9">
                        <input id="requestdate" class="form-control" asp-for="@requestedate" readonly />
                        <span class="text-danger" asp-validation-for="@requestedate"></span>
                    </div>
                </div>

                @if (Model.DayObj.Id != 0)
                {
                    <div class="form-group row">
                        <div class="col-3">
                            <label asp-for="DayObj.Day"></label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" asp-for="DayObj.Day" readonly />
                            <span class="text-danger" asp-validation-for="DayObj.Day"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-3">
                            <label asp-for="DayObj.Date"></label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="datepicker" value="@Model.DayObj.Date.ToShortDateString()" type="text" asp-for="DayObj.Date" data-val="true" />
                            <span class="text-danger" asp-validation-for="DayObj.Date"></span>
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group row">
                        <div class="col-3">
                            <label asp-for="DayObj.Date"></label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="datepicker" value="@currentdate.ToShortDateString()" type="text" asp-for="DayObj.Date" data-val="true" />
                            <span class="text-danger" asp-validation-for="DayObj.Date"></span>
                        </div>
                    </div>
                }



                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="DayObj.Hours"></label>
                    </div>
                    <div class="col-9">
                        <input id="txtHours" class="form-control" asp-for="DayObj.Hours" />
                        <span class="text-danger" asp-validation-for="DayObj.Hours"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-9 offset-3">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" id="btnPlaceOrder" onclick="return validateInput()" value="Add Day" class="btn btn-primary form-control">
                                    @(Model.DayObj.Id != 0 ? "Update" : "Add")
                                </button>
                                @*<button type="submit" onclick="return validateInput()" class="btn btn-primary form-control">@(Model.DayObj.Id != 0 ? "Update" : "Add")</button>*@
                            </div>
                            <div class="col-6">
                                <a asp-page="./Details" asp-route-id="@Model.DayObj.TaskId" class="btn btn-success form-control">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
    <script>

        $(function () {
            $("#datepicker").datepicker({
                dateFormat: 'dd.MM.yy',
                changeMonth: true,
                changeYear: true
            });
        });

    </script>

    <script>
        function validateInput() {
            var rd = document.getElementById("requestdate").value;
            var dt = document.getElementById("datepicker").value;
            var hours = document.getElementById("txtHours").value;

            d1 = Date.parse(dt.toString());
            d2 = Date.parse(rd.toString());

            if (d1 > d2) {
                swal("Error", "Worked day should not exceed a requested date", "error");
                return false;
            }

            if (hours == 0) {
                swal("Error", "Hours should be greater than zero !", "error");
                return false;
            }
            return true;
        }
    </script>
}