TMS/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TMS.DataAccess.Data.Repository.IRepository;
using TMS.Utility;

namespace TMS.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ReportController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ReportController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return Json(new { data = _unitOfWork.Task.GetAll(includeProperties: "Priority,ApplicationUser", filter: c => c.UserId == claim.Value && c.Status == Constant.StatusClosed) });
        }

        [HttpPost]
        public IActionResult Get(string date)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            DateTime currdate = Convert.ToDateTime(date);

            var tasks = _unitOfWork.Task.GetAll(includeProperties: "Priority,ApplicationUser", filter: c => c.UserId == claim.Value && c.Status == Constant.StatusClosed && c.ClosedOn.Month == currdate.Month && c.ClosedOn.Year == currdate.Year);

            if(tasks.Count() > 0)
            {
                return Json(new { data = tasks, success = true, message = "Success !" });
            }
            else
            {
                return Json(new { data = tasks, success = false, message = "No task found !" });
            }
        }

    }
}

TMS/Pages/Admin/Report/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.draw;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMS.DataAccess;
using TMS.DataAccess.Data.Repository.IRepository;
using TMS.Models;
using TMS.Models.ViewModels;
using TMS.Utility;

namespace TMS.Pages.Admin.Report
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public IndexModel(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
        }


        [BindProperty]
        public ReportViewModel ReportObj { get; set; }

        public void OnGet(string date)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (date != null)
            {
                DateTime currdate = Convert.ToDateTime(date);
                ReportObj = new ReportViewModel()
                {
                    CurrentDate = currdate,
                    Tasks = _unitOfWork.Task.GetAll(includeProperties: "Priority,ApplicationUser", filter: c => c.UserId == claim.Value && c.Status == Constant.StatusClosed && c.ClosedOn.Month == currdate.Month && c.ClosedOn.Year == currdate.Year)
                };
            }
            else
            {
                DateTime currdate = DateTime.Today;
                ReportObj = new ReportViewModel()
                {
                    CurrentDate = currdate,
                    Tasks = _unitOfWork.Task.GetAll(includeProperties: "Priority,ApplicationUser", filter: c => c.UserId == claim.Value && c.Status == Constant.StatusClosed && c.ClosedOn.Month == currdate.Month && c.ClosedOn.Year == currdate.Year)
                };
            }
                       
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            return RedirectToPage("Index", new { date = ReportObj.CurrentDate.ToShortDateString()});
        }

        public IActionResult OnPostPrint()
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            DateTime currdate = ReportObj.CurrentDate;

            IEnumerable<CTask> Tasks = _unitOfWork.Task.GetAll(includeProperties: "Priority,ApplicationUser", filter: c => c.UserId == claim.Value && c.Status == Constant.StatusClosed && c.ClosedOn.Month == currdate.Month && c.ClosedOn.Year == currdate.Year);

            DataTable table = GetReportTable(Tasks);
            //MemoryStream mstream = GenerateReport(table, @"E:\Reports\test.pdf", "Report");

            MemoryStream mstream = GenerateReport(Tasks.ToList());

            return new FileStreamResult(mstream, "application/pdf");

            //return RedirectToPage("Index", new { date = ReportObj.CurrentDate.ToShortDateString() });
        }

        public MemoryStream GenerateReport(List<CTask> Tasks)
        {
            double hours = GetTotalOfHours(Tasks);

            DataTable table = GetReportTable(Tasks);
            //MemoryStream memoryStream = GenerateReport(table, hours);

            MemoryStream memoryStream = new MemoryStream();
            //FileStream fs = new FileStream(@"E:\Reports\test.pdf", FileMode.Create, FileAccess.Write, FileShare.None);
            Document pdfDoc = new Document(PageSize.A4, 50, 50, 50, 50);
            //PdfWriter writer = PdfWriter.GetInstance(pdfDoc, fs);
            PdfWriter writer = PdfWriter.GetInstance(pdfDoc, memoryStream);

            string webRootPath = _hostingEnvironment.WebRootPath;
            var logoPath = Path.Combine(webRootPath, @"images\logo\Logo.png");

            var titleFont = FontFactory.GetFont("Arial", 12, Font.BOLD);
            var titleFontBlue = FontFactory.GetFont("Arial", 14, Font.NORMAL);
            //var titleFontBlue = FontFactory.GetFont("Arial", 14, Font.NORMAL, BaseColor.DARK_GRAY);
            var boldTableFont = FontFactory.GetFont("Arial", 9, Font.BOLD);
            var bodyFont = FontFactory.GetFont("Arial", 9, Font.NORMAL);
            var EmailFont = FontFactory.GetFont("Arial", 8, Font.NORMAL);
            BaseColor TabelHeaderBackGroundColor = BaseColor.LIGHT_GRAY;


            Rectangle pageSize = writer.PageSize;
            // Open the Document for writing
            pdfDoc.Open();
            //Add elements to the document here

            #region Top table
            // Create the header table 
            PdfPTable headertable = new PdfPTable(3);
            headertable.HorizontalAlignment = 0;
            headertable.WidthPercentage = 100;
            headertable.SetWidths(new float[] { 100f, 300f, 120f });
            headertable.DefaultCell.Border = Rectangle.NO_BORDER;

            Image logo = Image.GetInstance(logoPath);

            logo.ScaleToFit(100, 15);

            {
                PdfPCell pdfCelllogo = new PdfPCell(logo);
                pdfCelllogo.Border = Rectangle.NO_BORDER;
                pdfCelllogo.BorderColorBottom = new BaseColor(System.Drawing.Color.Black);
                pdfCelllogo.BorderWidthBottom = 1f;
                headertable.AddCell(pdfCelllogo);
            }

            {
                PdfPCell middlecell = new PdfPCell();
                middlecell.Border = Rectangle.NO_BORDER;
                middlecell.BorderColorBottom = new BaseColor(System.Drawing.Color.Black);
                middlecell.BorderWidthBottom = 1f;
                headertable.AddCell(middlecell);
            }

            {
                PdfPTable nested = new PdfPTable(1);
                nested.DefaultCell.Border = Rectangle.NO_BORDER;
                PdfPCell nextPostCell1 = new PdfPCell(new Phrase("KenffySoft GmbH", titleFont));
                nextPostCell1.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell1);
                PdfPCell nextPostCell2 = new PdfPCell(new Phrase("Rosengartenstraße 25", bodyFont));
                nextPostCell2.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell2);
                PdfPCell nextPostCell3 = new PdfPCell(new Phrase("73614 Schorndorf", bodyFont));
                nextPostCell3.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell3);
                PdfPCell nextPostCell4 = new PdfPCell(new Phrase("kenffysoft@gmail.com", EmailFont));
                nextPostCell4.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell4);
                nested.AddCell("");
                PdfPCell nesthousing = new PdfPCell(nested);
                nesthousing.Border = Rectangle.NO_BORDER;
                nesthousing.BorderColorBottom = new BaseColor(System.Drawing.Color.Black);
                nesthousing.BorderWidthBottom = 1f;
                nesthousing.Rowspan = 5;
                nesthousing.PaddingBottom = 10f;
                headertable.AddCell(nesthousing);
            }

            PdfPTable Invoicetable = new PdfPTable(3);
            Invoicetable.HorizontalAlignment = 0;
            Invoicetable.WidthPercentage = 100;
            Invoicetable.SetWidths(new float[] { 220f, 180f, 120f });  // then set the column's __relative__ widths
            Invoicetable.DefaultCell.Border = Rectangle.NO_BORDER;


            {
                PdfPTable nested = new PdfPTable(1);
                nested.DefaultCell.Border = Rectangle.NO_BORDER;
                PdfPCell nextPostCell1 = new PdfPCell(new Phrase("", bodyFont));
                nextPostCell1.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell1);
                PdfPCell nextPostCell2 = new PdfPCell(new Phrase("Voufo Kenfack, Marius Davy", titleFont));
                nextPostCell2.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell2);
                PdfPCell nextPostCell3 = new PdfPCell(new Phrase("Musterstraße 20, 73884 Musterstadt", bodyFont));
                nextPostCell3.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell3);
                PdfPCell nextPostCell4 = new PdfPCell(new Phrase("mustermann@example.com", EmailFont));
                nextPostCell4.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell4);
                nested.AddCell("");
                PdfPCell nesthousing = new PdfPCell(nested);
                nesthousing.Border = Rectangle.NO_BORDER;
                //nesthousing.BorderColorBottom = new BaseColor(System.Drawing.Color.Black);
                //nesthousing.BorderWidthBottom = 1f;
                nesthousing.Rowspan = 5;
                nesthousing.PaddingBottom = 10f;
                Invoicetable.AddCell(nesthousing);
            }

            {
                PdfPCell middlecell = new PdfPCell();
                middlecell.Border = Rectangle.NO_BORDER;
                //middlecell.BorderColorBottom = new BaseColor(System.Drawing.Color.Black);
                //middlecell.BorderWidthBottom = 1f;
                Invoicetable.AddCell(middlecell);
            }


            {
                PdfPTable nested = new PdfPTable(1);
                nested.DefaultCell.Border = Rectangle.NO_BORDER;
                PdfPCell nextPostCell1 = new PdfPCell(new Phrase("TMS Report", titleFontBlue));
                nextPostCell1.Border = Rectangle.NO_BORDER;
                nested.AddCell(nextPostCell1);

TMS/Pages/Admin/Report/Index.cshtml
@page
@model TMS.Pages.Admin.Report.IndexModel


<div class="">
    <form method="post">
        <input type="hidden" asp-for="ReportObj.Tasks"/>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="container backgroundWhite">
            <div class="card">
                <div class="card-header bg-light text-light ml-0 row container">
                    <div class="col-12 col-md-6">
                        <h3 class="text-secondary"><strong>Reports</strong></h3>
                    </div>
                    <div class="col-12 col-md-6 text-md-right">
                        <button type="submit" asp-page-handler="Print" class="btn btn-warning form-control text-white" style="cursor:pointer; width:100px;">
                            Print
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-8">
                                <div class="row">

                                    <div class="col-12">

                                        <div class="form-group row">
                                            <div class="col-3">
                                                <label asp-for="ReportObj.CurrentDate"></label>
                                            </div>
                                            <div class="col-6">
                                                <input class="form-control" asp-for="ReportObj.CurrentDate"/>
                                                <span class="text-danger" asp-validation-for="ReportObj.CurrentDate"></span>
                                            </div>
                                            <div class="col-2 ml-0">
                                                <button type="submit" class="btn btn-secondary form-control text-white" style="cursor:pointer; width:100px;">
                                                    Search
                                                </button>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    @if (Model.ReportObj.Tasks.Count() > 0)
                    {
                        <table class="table table-striped border">
                            <tr class="table-secondary">
                                <th>
                                    <label>Name</label>
                                </th>
                                <th>
                                    <label>Customer</label>
                                </th>
                                <th>
                                    <label>Requested Date</label>
                                </th>
                                <th>
                                    <label>Hours</label>
                                </th>
                                <th>
                                    <label>Priority</label>
                                </th>
                                <th>
                                    <label>Status</label>
                                </th>
                            </tr>
                            @foreach (var item in Model.ReportObj.Tasks)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(m => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => item.Customer)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => item.RequestDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => item.TotalOfHours)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => item.Priority.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => item.Status)
                                    </td>
                                </tr>
                            }
                        </table>
                    }
                    else
                    {
                        <p>No closed tasks available.</p>
                    }

                </div>
            </div>
        </div>
    </form>
</div>


@section Scripts{


<script>
    var dataTable;

    $(document).ready(function () {
        loadList();
    });

    function loadList() {

        var dt = document.getElementById("currentmonth").value;
        dt = dt.toString();

        dataTable = $('#DT_load').DataTable({
            "ajax": {
                "url": "/api/Report?date="+dt,
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                { "data": "name", "width": "25%" },
                { "data": "customer", "width": "20%" },
                { "data": "requestDate", "width": "20%" },
                { "data": "totalOfHours", "width": "10%" },
                { "data": "priority.name", "width": "15%" },
                { "data": "status", "width": "10%" }
            ],
            "language": {
                "emptyTable": "no data found."
            },
            "width": "100%",
            "order": [[2, "asc"]]
        });
        
    }

    $(function () {
        $("#currentmonth").datepicker({
            dateFormat: 'dd.MM.yy',
            changeMonth: true,
            changeYear: true
        });
    });
</script>
}